# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1,2,3,5,8,13,21,34....
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

lim = 4000000
fibonaciset = [1,2]
sum = 0

# create fibonaci set
for i in range(3,lim):
    next = fibonaciset[i-2] + fibonaciset[i-3]
    if next > lim:
        break
    elif next % 2 == 0:
        sum = sum + next

    fibonaciset.append(next)

print(sum + 2)

